const options = [
  { value: "random", label: "Random" },
  { value: "business", label: "Business" },
  { value: "change", label: "Change" },
  { value: "character", label: "Character" },
  { value: "competition", label: "Competition" },
  { value: "education", label: "Education" },
  { value: "famous-quotes", label: "Famous Quotes" },
  { value: "film", label: "Film" },
  { value: "freedom", label: "Freedom" },
  { value: "friendship", label: "Friendship" },
  { value: "future", label: "Future" },
  { value: "happiness", label: "Happiness" },
  { value: "history", label: "History" },
  { value: "humorous", label: "Humorous" },
  { value: "inspirational", label: "Inspirational" },
  { value: "life", label: "Life" },
  { value: "love", label: "Love" },
  { value: "motivational", label: "Motivational" },
  { value: "philosophy", label: "Philosophy" },
  { value: "politics", label: "Politics" },
  { value: "science", label: "Science" },
  { value: "sports", label: "Sports" },
  { value: "success", label: "Success" },
  { value: "technology", label: "Technology" },
  { value: "wisdom", label: "Wisdom" },
];

export default options;
